### ISSUE TITLE
Register v2: post-launch tasks

### ISSUE THREAD

**Issue by StephenAbbott** [openownership/register#186]
- [ ] Task C1: Configure dev and test buckets if necessary for S3
- [ ] Task C2: Configure dev and test settings for S3
- [x] Task C3: Configure dev and test users for Elasticsearch
- [x] Task C4: Configure Review apps on Heroku for Register V2
- [x] Task C5: Turn off dynos for legacy Register application
- [x] Task C6: Merge Register-v2 fork into Register repository
- [x] Task C7: Cleanup legacy data and buckets on S3 which is no longer required

For @spacesnottabs and @tiredpixel to spec out and update

**Comment by tiredpixel** [comment]
### Task C4: Configure Review apps on Heroku for Register V2

Configure Heroku `openownership-register-v2` pipeline to enable review apps. This will enable Heroku apps to be automatically created for GitHub PRs, enabling functionality for complex pieces of work to be more easily tested prior to merge. The environment variables should be similar to existing `stag` app, but use the new Elasticsearch and AWS IAM users already created with `uat` suffix.

It might be worth renaming existing `stag` app at the same time, to change the URL to the new Heroku format (which includes a random component), and make the suffixes `dev`, `uat`, `stg`, `prd` (rather than `stag` or `staging`).

_Estimate: 1h30_

**Comment by tiredpixel** [comment]
@StephenAbbott, could I please just double-check that C5 is approved—that is, getting rid of register-v1 on Heroku?

**Comment by StephenAbbott** [comment]
@tiredpixel Yes. C5 is approved

**Comment by tiredpixel** [comment]
C4 is done. Review apps will build automatically once PR #193 is in.

**Comment by tiredpixel** [comment]
@spacesnottabs, when you get some time, I think all that is remaining from this ticket is for you to clarify or spec C1, C2, C7. Thanks!

**Comment by tiredpixel** [comment]
Spec for remaining tasks (by @spacesnottabs):

[Post launch tasks.pdf](https://github.com/openownership/register/files/13251575/Post.launch.tasks.pdf)

**Comment by tiredpixel** [comment]
Task C7 is blocked by https://github.com/openownership/register/issues/213 . Since nothing on this list is urgent, I'm pausing any work on this until after that ticket, and changing the state of this ticket to reflect that.

**Comment by tiredpixel** [comment]
### Task C1: Configure dev and test buckets if necessary for S3

Currently there is just the single bucket used bu the ingesters and transformers (oo-register-v2).

When testing changes to ingestors or transformers, it would be better for a test (or dev) environment to use different S3 buckets, Elasticsearch indexes, and Kinesis streams.

- Setup test S3 bucket
- Setup a test Kinesis stream
- Setup Firehose to write output of Kinesis stream to new S3 bucket

This should also be done to separate staging from production, as well as for local dev.

**Comment by tiredpixel** [comment]
### Task C2: Configure dev and test settings for S3

This requires updating any necessary config so that review apps for ingesters and transformers will use the new test buckets configured in C1.

- Review apps should use the bucket and Kinesis stream configured in C1
- Staging should use the bucket and Kinesis stream configured in C1

**Comment by tiredpixel** [comment]
### Task C7: Cleanup legacy data and buckets on S3 which is no longer required

Quite a lot of test data was produced which is not required.

**This task is blocked by first needing to replace the register-files-combiner.**

Remove the data in:

- s3://oo-register-v2/bods_v2_dk/source=DK/
- s3://oo-register-v2/bods_v2_sk/source=SK/
- s3://oo-register-v2/bods_v2_psc/source=PSC/
- s3://oo-register-v2/bods_v2_roe/source=ROE/

S3 bucket and data in:

- oo-register-dev
- oo-register-bods-exporter-bodsv2
- oo-register-bods-exporter-bodsv2combiner
- oo-register-bods-exporter-dev1
- oo-register-bods-exporter-roedev
- oo-register-exporter-prod1
- oo-register-exporter-staging-1
- oo-register-exporter-staging2
- oo-register-importer-devel100

**Comment by tiredpixel** [comment]
Since the new Register Files Combiner is complete, this task is no longer blocked by #213 .

**Comment by tiredpixel** [comment]
Task C7 cleanup is complete. I think there might still be some unused S3 buckets, but if they weren't mentioned here, I didn't delete them.

I did, however, also clean up `backups/` in oo-register-v2, and move another file.

**Comment by tiredpixel** [comment]
Which approach would be best for Tasks C1 and C2 depends rather on the upcoming roadmap. Rather than spend time configuring and testing these for something which might not currently need active development, I suggest that we instead leave those tasks undone, for now, but instead add do them when the need arises during future development. In which case, I'd suggest closing this ticket, since it's already quite long after Register 2 release, and there isn't anything important left, from what I can see.

What do you think, @StephenAbbott ? Should we close the ticket and leave Tasks C1 and C2 undone for now?

**Comment by StephenAbbott** [comment]
Sounds good @tiredpixel. Will close
