### ISSUE TITLE
Refactor Ingester OC lib dir

### ISSUE THREAD

**Issue by tiredpixel** [openownership/register#219]
A lot of cross-repository duplication was found in Register Ingester OC `lib/` `add_ids`, `alt_names`, `companies` directories.

Investigate whether these can be refactored conveniently.

This doesn't necessary have to wait for a broader discussion on Register multi-repo structure, since although it would be affected, there is plenty to be done in the existing folders, since the duplication is extensive.

This is a spin-off ticket from https://github.com/openownership/register/issues/188 .

**Comment by tiredpixel** [comment]
### TODO

- [ ] add_ids/conversion_service.rb
- [ ] alt_names/conversion_service.rb
- [ ] companies/conversion_service.rb
- [ ] add_ids/create_tables_service.rb
- [ ] alt_names/create_tables_service.rb
- [ ] companies/create_tables_service.rb
- [ ] add_ids/exporter_service.rb
- [ ] alt_names/exporter_service.rb
- [ ] companies/exporter_service.rb

No need to refactor */create_tables_service.rb (3), since it already inherits a class, or */row_processor.rb (3), since it is very small.
